# Static Summarizer for Demo

def summarizer(transcript):
    return """
## 🔥 Demo Summary (Static)

- This is a demo summary for presentation purposes.
- In the full version, this summary is generated by Llama3.1 using Ollama locally.
- The transcript is fetched in real-time, but the summary here is static.

---

👉 To run the full AI-powered version locally, clone the main repo and follow instructions in README.
"""
